apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-frontend
  template:
    metadata:
      labels:
        app: vote-frontend
    spec:
      containers:
      - name: vote-frontend
        image: image-registry.openshift-image-registry.svc:5000/demo/vote-frontend:v2
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
        env:
        - name: REDIS
          value: "vote-backend"
---
apiVersion: v1
kind: Service
metadata:
  name: vote-frontend
spec:
  ports:
  - port: 8080
  selector:
    app: vote-frontend
